os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash

init:

install:

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm install -r coreclr -arch x64 1.0.0-beta8-15618 -OS win -u"'
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm use -r coreclr -arch x64 1.0.0-beta8-15618 -p; dnvm list; dnu.cmd --help"'

