os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash
  CYGWIN: NONTSEC

init:

install:

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm upgrade; mkdir $DNX_USER_HOME/alias; dnvm install -r coreclr -arch x64 latest -OS win -u; dnvm list; cd $DNX_USER_HOME; ls -A; echo OK"'
 