os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash
  CYGWIN: NONTSEC

init:

install:
  - '%CYG_BASH% -lc "echo WHY; echo /cygdrive/c/Users/slofurno/.dnx:/usr/local/lib/dnx | tr \":\" \"\n\"; echo NOT"'

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm upgrade; dnvm install -r coreclr -arch x64 latest -OS win -u; dnvm list;dnu.cmd"'


