
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

install:
  - cinst cygwin -y

build_script:

