os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash
  CYGWIN: NONTSEC

init:

install:
  - '%CYG_BASH% -lc "mkdir $HOMEPATH/.dnx/; mkdir $HOMEPATH/.dnx/runtimes"'

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm install -r coreclr -arch x64 latest -OS win -u; dnvm list;dnu.cmd"'


